name: Generate NuGet and push to Github

on:
  workflow_call:
    inputs:
      DOTNET_PROJECT:
        required: true
        type: string
      DOTNET_CSPROJ: 
        type: string
        required: true
      RESTORE_SOURCES:
        type: string
        required: true
      CONFIGURATION:
        required: true
        type: string
      FRAMEWORK: 
        type: string
        required: true
      RUNTIME:
        required: true
        type: string
      ADDITIONAL_PROPERTIES: 
        type: string
        required: false
    secrets:
      GPACKAGES_TOKEN:
        required: true

jobs:
  generate-nuget-and-push:
    runs-on: self-hosted
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          #submodules: false
          #lfs: true
          clean: true
          fetch-depth: 0 # Required, without this get_previous_tag action won't be able to find any or the correct tags

      - name: Check initial folder
        run: |
          echo "Checked out code"
          ls -la
          
      - name: Output debug information
        id: path_definition
        run: |
          echo $PWD
          echo ${GITHUB_WORKSPACE}/src
          
      - name: Extract Git Branch information
        id: branch_name
        run: |
          MBRANCH=${GITHUB_REF#refs/*/}
          GITSHA=${GITHUB_SHA::8}
          if [[ $MBRANCH == feature/* ]]; then
            BRANCH="a-${MBRANCH#feature/}.$(date +%Y%m%d%H%M)"
          elif [[ $MBRANCH == "master" ]] || [[ $MBRANCH == "main" ]]; then
            BRANCH="" ;
          else
            BRANCH="${MBRANCH}.$(date +%Y%m%d%H%M)"
          fi
          echo BRANCH: $BRANCH
          echo ::set-output name=BRANCH::$BRANCH

      - name: Get Previous Tag
        id: get_previous_tag
        #uses: WyriHaximus/github-action-get-previous-tag@v1
        run: |
          VERSIONPROPS=$(cat Directory.Build.props | grep "[0-9].[0.9].[0-9]" | sed "s+<VersionPrefix>++g" | sed "s+</VersionPrefix>++g")
          echo ::set-output name=tag::$VERSIONPROPS
        
      - name: Set VERSION variable from latest tag
        id: version_num
        run: |
          echo ::set-output name=VERSION::${{ steps.get_previous_tag.outputs.tag }}

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Add old nuget source (temporarily)
        continue-on-error: true
        # In case it was already added.
        run:  dotnet nuget add source -u hgr -p hgrpass -n hgrCluster --valid-authentication-types basic https://nuget.hustlegotreal.net/v3/index.json --store-password-in-clear-text

      #- name: Clean
      #  run: dotnet clean --framework ${{ inputs.FRAMEWORK }} --runtime ${{ inputs.RUNTIME }} --configuration ${{ inputs.CONFIGURATION }} && dotnet nuget locals all --clear
        
      - name: Restore
        run: |
             dotnet restore /property:Configuration=${{ inputs.CONFIGURATION }} /property:TargetFramework=${{ inputs.FRAMEWORK }} --runtime ${{ inputs.RUNTIME }} \
             ${{ inputs.DOTNET_CSPROJ }} ${{ inputs.RESTORE_SOURCES }}
        
      - name: Build
        run: |
             dotnet build --no-restore -f ${{ inputs.FRAMEWORK }} -r ${{ inputs.RUNTIME }} ${{ inputs.DOTNET_CSPROJ }} /property:Configuration=${{ inputs.CONFIGURATION }} ${{ inputs.ADDITIONAL_PROPERTIES }} \
             /p:VersionPrefix=${{ steps.version_num.outputs.VERSION }} /p:VersionSuffix=${{ steps.branch_name.outputs.BRANCH }}

      - name: Pack
        run: dotnet pack ${{ inputs.DOTNET_CSPROJ }} --no-restore -c ${{ inputs.CONFIGURATION }} /p:VersionPrefix=${{ steps.version_num.outputs.VERSION }} /p:VersionSuffix=${{ steps.branch_name.outputs.BRANCH }} --output nupkg-tmp/

      - name: Install gpr tool for upload NuGets
        continue-on-error: true
        # In case it was already installed.
        run: dotnet tool install gpr -g

      - name: Push
        run: /root/.dotnet/tools/gpr push nupkg-tmp/${{ inputs.DOTNET_PROJECT }}.${{ steps.version_num.outputs.VERSION }}-${{ steps.branch_name.outputs.BRANCH }}.nupkg --repository https://github.com/HustleGotReal/nugets -k ${GPACKAGESTOKEN} \
             
        env:
          GPACKAGESTOKEN: ${{ secrets.GPACKAGES_TOKEN }}
