name: Generate NuGet and push to Github

on:
  workflow_call:
    inputs:
      DOTNET_PROJECT:
        required: true
        type: string
      DOTNET_CSPROJ: 
        type: string
        required: true
      RESTORE_SOURCES:
        type: string
        required: true
      CONFIGURATION:
        required: true
        type: string
      FRAMEWORK: 
        type: string
        required: true
      RUNTIME:
        required: true
        type: string
      ADDITIONAL_PROPERTIES: 
        type: string
        required: false
    secrets:
      GPACKAGES_TOKEN:
        required: true

jobs:
  generate-nuget-and-push:
    runs-on: self-hosted
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          #submodules: false
          #lfs: true
          clean: true
          fetch-depth: 0 # Required due to the weg Git works, without it get_previous_tag action won't be able to find any or the correct tags

      - name: Check initial folder
        run: |
          echo "Checked out code"
          ls -la
          
      - name: Output debug information
        id: path_definition
        run: |
          echo $PWD
          echo ${GITHUB_WORKSPACE}/src
          #echo "PROJECT_DIR=${GITHUB_WORKSPACE}/src" >> $GITHUB_ENV
          #echo ::set-output name=PROJECT_DIR::"${GITHUB_WORKSPACE}/src"
          
      - name: Extract Git Branch information
        id: branch_name
        run: |
          MBRANCH=${GITHUB_REF#refs/*/}
          GITSHA=${GITHUB_SHA::8}
          BRANCH="-${MBRANCH#feature/}.$(date +%Y%m%d%H%M)"
          if [["$BRANCH" == -master* ]] || [["$BRANCH" == -main* ]]; then BRANCH="";fi
          echo BRANCH: $BRANCH;
          echo ::set-output name=BRANCH::$BRANCH
          
      #- name: Set VERSION variable from tag.
      ## It only works if it is the same tag that triggered the workflow.
      #  id: version_num
      #  run: |
      #    TMPVERSION="${GITHUB_REF/refs\/tags\//}"
      #    echo VERSION: $TMPVERSION
      #    echo ::set-output name=VERSION::$TMPVERSION

      - name: Get Previous Tag
        id: get_previous_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        
      - name: Set VERSION variable from latest tag
        id: version_num
        run: |
             echo ::set-output name=VERSION::${{ steps.get_previous_tag.outputs.tag }}

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Add old nuget source
        continue-on-error: true
        run:  dotnet nuget add source -u hgr -p hgrpass -n hgrCluster --valid-authentication-types basic https://nuget.hustlegotreal.net/v3/index.json --store-password-in-clear-text

      #- name: Clean
      #  run: dotnet clean --framework ${{ inputs.FRAMEWORK }} --runtime ${{ inputs.RUNTIME }} --configuration ${{ inputs.CONFIGURATION }} && dotnet nuget locals all --clear
        
      - name: Restore
        run: |
             dotnet restore /property:Configuration=${{ inputs.CONFIGURATION }} /property:TargetFramework=${{ inputs.FRAMEWORK }} --runtime ${{ inputs.RUNTIME }} \
             ${{ inputs.DOTNET_CSPROJ }} ${{ inputs.RESTORE_SOURCES }}
        
      - name: Build
        run: |
             dotnet build --no-restore -f ${{ inputs.FRAMEWORK }} -r ${{ inputs.RUNTIME }} ${{ inputs.DOTNET_CSPROJ }} /property:Configuration=${{ inputs.CONFIGURATION }} ${{ inputs.ADDITIONAL_PROPERTIES }} \
             /p:Version=${{ steps.version_num.outputs.VERSION }}${{ steps.branch_name.outputs.BRANCH }}

      - name: Pack
        run: dotnet pack ${{ inputs.DOTNET_CSPROJ }} --no-restore -c ${{ inputs.CONFIGURATION }} /p:Version=${{ steps.version_num.outputs.VERSION }}${{ steps.branch_name.outputs.BRANCH }} --output nupkg-tmp/

      - name: Push
        run: dotnet nuget push nupkg-tmp/${{ inputs.DOTNET_PROJECT }}.${{ steps.version_num.outputs.VERSION }}${{ steps.branch_name.outputs.BRANCH }}.nupkg --source https://nuget.pkg.github.com/HustleGotReal/index.json --api-key ${GPACKAGESTOKEN}
        env:
          GPACKAGESTOKEN: ${{ secrets.GPACKAGES_TOKEN }}
