
name: Reload app on the server
on:
  workflow_call:
    inputs:
      RELOAD_COMMAND:
        required: true
        type: string
    secrets:
      SSH_USER:
        required: true
      SSH_PASSWORD:
        required: true

jobs:
  build-and-push-image:
    runs-on: self-hosted

    outputs:
      tag: ${{ steps.branch_name.outputs.SOURCE_TAG }}

    steps:
      - name: Extract Git Branch information
        id: branch_name
        run: |
          MBRANCH=${GITHUB_REF#refs/*/}
          BRANCH=${MBRANCH#feature/}
          echo "BRANCH: $BRANCH";
          [[ ! "$BRANCH" =~ ^master|[0-9]+\.[0-9]+\.[0-9]+$ ]] && BRANCH="${BRANCH}$(date +%s)"

          echo "SOURCE_TAG=$BRANCH" >> $GITHUB_OUTPUT
          echo "Started by: $GITHUB_ACTOR | SHA: $GITHUB_SHA"

      - name: Execute remote ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: browserless.hustlegotreal.net
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: ${{ inputs.RELOAD_COMMAND }}
