
name: Reload app on the server
on:
  workflow_call:
    inputs:
      RELOAD_COMMAND:
        required: true
        type: string
    secrets:
      SSH_USER:
        required: true
      SSH_PRIVATE_KEY:
        required: true

jobs:
  build-and-push-image:
    runs-on: self-hosted

    outputs:
      tag: ${{ steps.branch_name.outputs.SOURCE_TAG }}

    steps:
      - name: Extract Git Branch information
        id: branch_name
        run: |
          MBRANCH=${GITHUB_REF#refs/*/}
          BRANCH=${MBRANCH#feature/}
          echo "BRANCH: $BRANCH";
          [[ ! "$BRANCH" =~ ^master|[0-9]+\.[0-9]+\.[0-9]+$ ]] && BRANCH="${BRANCH}$(date +%s)"

          echo "SOURCE_TAG=$BRANCH" >> $GITHUB_OUTPUT
          echo "Started by: $GITHUB_ACTOR | SHA: $GITHUB_SHA"

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Using user with limited permissions
      - name: Restart app
        run: |
          ssh ${{ secrets.SSH_USER }}@browserless.hustlegotreal.net "${{ inputs.RELOAD_COMMAND }}"
