name: Sync ArgoCD app

on:
  workflow_call:
    inputs:
      ARGOCD_APPLICATION:
        type: string
        required: true
      CUSTOM_TIMEOUT
        type: number
        required: false
    secrets:
      ARGOCD_TOKEN:
        required: true

jobs:
  sync-app:
    runs-on: self-hosted
    steps:
      - name: ArgoCD authentication
        run: argocd login grpc-argocd.hustlegotreal.net --username=syncmaster --password='${{ secrets.ARGOCD_TOKEN }}'

      - name: ArgoCD app sync (dry-run)
        run: argocd app sync ${{ inputs.ARGOCD_APPLICATION }} --dry-run

      - name: ArgoCD app sync
        run: argocd app sync ${{ inputs.ARGOCD_APPLICATION }} --force
        
      - name: Verify app status
        run: argocd app wait ${{ inputs.ARGOCD_APPLICATION }} --sync --health --timeout ${{ inputs.CUSTOM_TIMEOUT || 300 }}

