name: Update deployment manifest in argocd

on:
  workflow_call:
    inputs:
      K8S_RESOURCENAME:
        type: string
        required: true
      K8S_NAMESPACE:
        required: true
        type: string
      K8S_OBJECTTYPE:
        type: string
        required: true
      K8S_CONTAINERNAME:
        type: string
        required: true
      TAG:
        type: string
        required: true
    secrets:
      GITHUB_PAT:
        required: true

jobs:
  update_manifest:
    runs-on: self-hosted
    steps:
      - name: Checkout argocd repo & update manifest
        uses: actions/checkout@v3
        with:
          repository: HustleGotReal/argocd
          ref: master
          token: ${{ secrets.GITHUB_PAT }}
      - run: |
          MANIFEST=${{ inputs.K8S_NAMESPACE }}/${{ inputs.K8S_RESOURCENAME }}-${{ inputs.K8S_OBJECTTYPE }}
          # Update the version in the deployment manifest
          yq eval ".spec.template.spec.containers(name==${{ inputs.K8S_CONTAINERNAME }}).image |= sub(\":.*\",\":${{ inputs.TAG }}\")" "${MANIFEST}.yaml"

          # Push a commit
          git config user.name hgrbot
          git config user.email hgrbot@gmail.com
          git add ${MANIFEST}.yaml
          git commit -m "Upload ${{ inputs.K8S_RESOURCENAME }} to version ${{ inputs.TAG }}"
          git push
