name: Update deployment manifest in argocd

on:
  workflow_call:
    inputs:
      DOCKER_IMAGEBASE:
        type: string
        required: true
      K8S_RESOURCENAME:
        type: string
        required: true
      K8S_NAMESPACE:
        required: true
        type: string
      K8S_OBJECTTYPE:
        type: string
        required: true
      K8S_CONTAINERNAME:
        type: string
        required: true
      TAG:
        type: string
        required: true
    secrets:
      GITHUB_PAT:
        required: true

jobs:
  update_manifest:
    runs-on: self-hosted
    steps:

      - name: Checkout argocd repository
        uses: actions/checkout@v3
        with:
          repository: HustleGotReal/argocd
          token: ${{ secrets.GITHUB_PAT }}

      - name: Check initial folder
        run: |
          echo "Checked out code"
          ls -la
          echo $PWD

      - name: Edit file
        run: |
          cd ${{ inputs.K8S_NAMESPACE }}/${{ inputs.K8S_RESOURCENAME }} && ls -la
          yq eval '.spec.template.spec.containers = [(.spec.template.spec.containers[] | select(.name == "${{ inputs.K8S_CONTAINERNAME }}") | .image = "${{ inputs.DOCKER_IMAGEBASE }}:${{ inputs.TAG }}")]' \
          "${{ inputs.K8S_RESOURCENAME }}-${{ inputs.K8S_OBJECTTYPE }}.yaml" -i

      - name: Commit changes
        if: git status --porcelain
        run: |
          git config user.name hgrbot
          git config user.email hgrbot@gmail.com
          git add .
          git commit -m "Upload ${{ inputs.K8S_RESOURCENAME }} to version ${{ inputs.TAG }}"

      - name: Push changes
        if: git status --porcelain
        run: |
          git push origin master
