name: Update deployment manifest in argocd

on:
  workflow_call:
    inputs:
      DOCKER_IMAGEBASE:
        type: string
        required: true
      K8S_RESOURCENAME:
        type: string
        required: true
      K8S_NAMESPACE:
        required: true
        type: string
      K8S_OBJECTTYPE:
        type: string
        required: true
      K8S_CONTAINERNAME:
        type: string
        required: true
      TAG:
        type: string
        required: true
    secrets:
      GITHUB_PAT:
        required: true

jobs:
  update_manifest:
    runs-on: self-hosted
    steps:

      - name: Checkout argocd repository
        uses: actions/checkout@v3
        with:
          repository: HustleGotReal/argocd
          token: ${{ secrets.GITHUB_PAT }}
          ref: master

      - name: Check initial folder
        run: |
          echo "Checked out code"
          ls -la
          echo $PWD

      - name: Edit file
        run: |
          IFS=',' read -ra RESOURCE_NAMES <<< "${{ inputs.K8S_RESOURCENAME }}"
          for RESOURCE_NAME in "${RESOURCE_NAMES[@]}"; do
           cd "${{ inputs.K8S_NAMESPACE }}/${RESOURCE_NAME}" || exit 1
           if [ "${{ inputs.K8S_OBJECTTYPE }}" = "cronjob" ]; then
             yq eval -i ".spec.jobTemplate.spec.template.spec.containers |= map(if .e.spec.template.spec.containers |= map(if .name == \"${{ inputs.K8S_CONTAINERNAME }}\" then .image = \"${{ inputs.DOCKER_IMAGEBASE }}:${{ inputs.TAG }}\" else . end)" "${RESOURCE_NAME}-${{ inputs.K8S_OBJECTTYPE }}.yaml"
           else
           yq eval -i ".spec.template.spec.containers |= map(if .name == \"${{ inputs.K8S_CONTAINERNAME }}\" then .image = \"${{ inputs.DOCKER_IMAGEBASE }}:${{ inputs.TAG }}\" else . end)" "${RESOURCE_NAME}-${{ inputs.K8S_OBJECTTYPE }}.yaml"
          fi
          done
      - name: Check changes
        id: check_changes
        run: |
          if git status --porcelain | grep -qE '^(M| M)'; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "There are no changes in git"
          fi

      - name: Verify YAML syntax
        if: steps.check_changes.outputs.changes != 'false'
        run: kubeconform -summary -output json ${{ inputs.K8S_NAMESPACE }}/${{ inputs.K8S_RESOURCENAME }}/${{ inputs.K8S_RESOURCENAME }}-${{ inputs.K8S_OBJECTTYPE }}.yaml

      - name: Commit changes
        if: steps.check_changes.outputs.changes != 'false'
        run: |
          git config user.name hgrbot
          git config user.email hgrbot@gmail.com
          git add .
          git commit -m "Upload ${{ inputs.K8S_RESOURCENAME }} to version ${{ inputs.TAG }}"

      - name: Push changes
        if: steps.check_changes.outputs.changes != 'false'
        run: |
          git push origin master
